export default [
  {
    id: 0,
    categoryId: 1,
    name: "Chiếc áo mới",
    description: "Áo mẹ mua",
    price: 300,
    distance: 100,
    favorite: false,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 0 },
    ],
    backgroundColor: "grey",
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
  },
  {
    id: 1,
    categoryId: 0,
    name: "mssssss",
    description: "Áo mẹ mua",
    price: 250,
    distance: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 2,
    categoryId: 3,
    name: "chọn",
    description: "Áo người yêu mua",
    price: 200,
    favorite: false,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#efeef3",
  },
  {
    id: 3,
    categoryId: 2,
    name: "s",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    favorite: true,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 4,
    categoryId: 1,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    favorite: true,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 5,
    categoryId: 2,
    name: "b",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 6,
    categoryId: 2,
    name: "a",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    favorite: true,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 7,
    categoryId: 2,
    name: "as",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    favorite: true,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 8,
    categoryId: 0,
    name: "Áo trắng",
    description: "Áo người yêu cũ mua",
    price: 100,
    distance: 100,
    favorite: false,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 9,
    categoryId: 1,
    name: "Hoodie B",
    description: "Áo khoác dày dặn",
    price: 500,
    distance: 150,
    options: [
      { color: "navy", quantity: 5 },
      { color: "gray", quantity: 5 },
      { color: "black", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 10,
    categoryId: 0,
    name: "Summer Breeze Dress",
    description: "Đầm xòe cổ tròn",
    price: 550,
    distance: 50,
    options: [
      { color: "blue", quantity: 5 },
      { color: "yellow", quantity: 5 },
      { color: "pink", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f6f2ed",
  },
  {
    id: 11,
    categoryId: 1,
    name: "Leather Ankle Boots",
    description: "Giày cao gót da thật",
    price: 850,
    distance: 10,
    options: [
      { color: "black", size: "36", quantity: 3 },
      { color: "black", size: "37", quantity: 4 },
      { color: "black", size: "38", quantity: 5 },
      { color: "brown", size: "36", quantity: 2 },
      { color: "brown", size: "37", quantity: 3 },
      { color: "brown", size: "38", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f7f7f7",
  },
  {
    id: 12,
    categoryId: 0,
    name: "new product",
    description: "Áo mới",
    price: 300,
    distance: 120,
    options: [
      { color: "blue", quantity: 15 },
      { color: "green", quantity: 15 },
      { color: "yellow", quantity: 15 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 13,
    categoryId: 0,
    name: "new product 2",
    description: "Áo mới 2",
    price: 350,
    distance: 150,
    options: [
      { color: "purple", quantity: 20 },
      { color: "orange", quantity: 20 },
      { color: "gray", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 14,
    categoryId: 0,
    name: "Áo thun",
    description: "Áo mới",
    price: 300,
    distance: 120,
    options: [
      { color: "blue", quantity: 15 },
      { color: "green", quantity: 15 },
      { color: "yellow", quantity: 15 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 15,
    categoryId: 0,
    name: "Áo len",
    description: "Áo mới 2",
    price: 350,
    distance: 150,
    options: [
      { color: "purple", quantity: 20 },
      { color: "orange", quantity: 20 },
      { color: "gray", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 16,
    categoryId: 0,
    name: "Áo khoác",
    description: "Áo mới 3",
    price: 450,
    distance: 200,
    options: [
      { color: "brown", quantity: 25 },
      { color: "navy", quantity: 25 },
      { color: "pink", quantity: 25 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 17,
    categoryId: 0,
    name: "Áo sơ mi",
    description: "Áo mới 4",
    price: 400,
    distance: 180,
    options: [
      { color: "light blue", quantity: 30 },
      { color: "gray", quantity: 30 },
      { color: "purple", quantity: 30 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 18,
    categoryId: 1,
    name: "Quần jean",
    description: "Quần mới 1",
    price: 500,
    distance: 220,
    options: [
      { color: "light blue", quantity: 20 },
      { color: "dark blue", quantity: 20 },
      { color: "black", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f8f6f7",
  },
  {
    id: 19,
    categoryId: 1,
    name: "Quần kaki",
    description: "Quần mới 2",
    price: 450,
    distance: 190,
    options: [
      { color: "beige", quantity: 25 },
      { color: "green", quantity: 25 },
      { color: "gray", quantity: 25 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f8f6f7",
  },
  {
    id: 20,
    categoryId: 1,
    name: "Quần tây",
    description: "Quần mới 3",
    price: 550,
    distance: 240,
    options: [
      { color: "black", quantity: 30 },
      { color: "gray", quantity: 30 },
      { color: "navy", quantity: 30 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f8f6f7",
  },
  {
    id: 21,
    categoryId: 2,
    name: "Giày thể thao",
    description: "Giày mới 1",
    price: 800,
    distance: 350,
    options: [
      { color: "white", quantity: 15 },
      { color: "black", quantity: 15 },
      { color: "gray", quantity: 15 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 22,
    categoryId: 2,
    name: "Giày bít",
    description: "Giày mới 2",
    price: 700,
    distance: 300,
    options: [
      { color: "brown", quantity: 20 },
      { color: "black", quantity: 20 },
      { color: "gray", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 23,
    categoryId: 2,
    name: "Dép",
    description: "Dép mới 1",
    price: 350,
    distance: 100,
    options: [
      { color: "blue", quantity: 25 },
      { color: "brown", quantity: 25 },
      { color: "black", quantity: 25 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 24,
    categoryId: 2,
    name: "Giày sandal",
    description: "Giày mới 3",
    price: 550,
    distance: 240,
    options: [
      { color: "white", quantity: 30 },
      { color: "black", quantity: 30 },
      { color: "brown", quantity: 30 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 25,
    categoryId: 2,
    name: "Giày boots",
    description: "Giày mới 4",
    price: 1000,
    distance: 400,
    options: [
      { color: "black", quantity: 20 },
      { color: "brown", quantity: 20 },
      { color: "gray", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f5f5f5",
  },
  {
    id: 26,
    categoryId: 0,
    name: "abcdefg",
    description: "Áo của tôi",
    price: 300,
    distance: 50,
    options: [
      { color: "blue", quantity: 10 },
      { color: "green", quantity: 10 },
      { color: "yellow", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 27,
    categoryId: 2,
    name: "T-shirt XYZ",
    description: "Áo thun của tôi",
    price: 250,
    distance: 80,
    options: [
      { color: "black", quantity: 8 },
      { color: "white", quantity: 12 },
      { color: "red", quantity: 6 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 28,
    categoryId: 1,
    name: "Summer Tee",
    description: "Áo thun mùa hè",
    price: 200,
    distance: 20,
    options: [
      { color: "pink", quantity: 5 },
      { color: "orange", quantity: 7 },
      { color: "gray", quantity: 3 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 29,
    categoryId: 3,
    name: "Vintage Tee",
    description: "Áo thun cổ điển",
    price: 180,
    distance: 45,
    options: [
      { color: "navy", quantity: 9 },
      { color: "olive", quantity: 11 },
      { color: "tan", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 30,
    categoryId: 2,
    name: "Graphic Tee",
    description: "Áo thun có hình",
    price: 300,
    distance: 70,
    options: [
      { color: "white", quantity: 8 },
      { color: "black", quantity: 12 },
      { color: "red", quantity: 6 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 31,
    categoryId: 1,
    name: "Basic Tee",
    description: "Áo thun cơ bản",
    price: 150,
    distance: 30,
    options: [
      { color: "gray", quantity: 7 },
      { color: "white", quantity: 8 },
      { color: "black", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 32,
    categoryId: 3,
    name: "Retro Tee",
    description: "Áo thun phong cách retro",
    price: 220,
    distance: 65,
    options: [
      { color: "yellow", quantity: 10 },
      { color: "orange", quantity: 8 },
      { color: "green", quantity: 6 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 34,
    categoryId: 1,
    name: "Plain Tee",
    description: "Áo thun trơn",
    price: 170,
    distance: 15,
    options: [
      { color: "black", quantity: 8 },
      { color: "white", quantity: 6 },
      { color: "navy", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 35,
    categoryId: 2,
    name: "Floral Tee",
    description: "Áo thun hoa",
    price: 260,
    distance: 60,
    options: [
      { color: "pink", quantity: 7 },
      { color: "blue", quantity: 9 },
      { color: "green", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 36,
    categoryId: 3,
    name: "Striped Tee",
    description: "Áo thun sọc",
    price: 190,
    distance: 40,
    options: [
      { color: "navy", quantity: 8 },
      { color: "red", quantity: 6 },
      { color: "gray", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 37,
    categoryId: 1,
    name: "Pocket Tee",
    description: "Áo thun túi",
    price: 210,
    distance: 25,
    options: [
      { color: "white", quantity: 6 },
      { color: "black", quantity: 8 },
      { color: "gray", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 38,
    categoryId: 2,
    name: "Logo Tee",
    description: "Áo thun có logo",
    price: 290,
    distance: 80,
    options: [
      { color: "white", quantity: 10 },
      { color: "black", quantity: 8 },
      { color: "red", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 44,
    categoryId: 2,
    name: "Raglan Tee",
    description: "Áo thun Raglan",
    price: 290,
    distance: 15,
    options: [
      { color: "white", quantity: 8 },
      { color: "black", quantity: 5 },
      { color: "gray", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 45,
    categoryId: 3,
    name: "Tank Top",
    description: "Áo thun nữ tank top",
    price: 200,
    distance: 20,
    options: [
      { color: "white", quantity: 9 },
      { color: "black", quantity: 5 },
      { color: "gray", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 46,
    categoryId: 1,
    name: "Baseball Tee",
    description: "Áo thun baseball",
    price: 300,
    distance: 60,
    options: [
      { color: "white", quantity: 7 },
      { color: "gray", quantity: 6 },
      { color: "black", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 47,
    categoryId: 2,
    name: "Ringer Tank",
    description: "Áo thun nữ ringer",
    price: 230,
    distance: 45,
    options: [
      { color: "white", quantity: 8 },
      { color: "navy", quantity: 5 },
      { color: "red", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 48,
    categoryId: 3,
    name: "Scoop Neck Tee",
    description: "Áo thun nữ cổ bẻ",
    price: 260,
    distance: 35,
    options: [
      { color: "white", quantity: 8 },
      { color: "black", quantity: 5 },
      { color: "gray", quantity: 4 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 50,
    categoryId: 0,
    name: "Eooooo",
    description: "Áo của bạn",
    price: 250,
    distance: 70,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 75,
    categoryId: 0,
    name: "xyz",
    description: "Áo của tôi",
    price: 350,
    distance: 60,
    options: [
      { color: "purple", quantity: 10 },
      { color: "orange", quantity: 10 },
      { color: "pink", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 52,
    categoryId: 0,
    name: "Áo Vmax",
    description: "Áo của bạn",
    price: 250,
    distance: 60,
    options: [
      { color: "blue", quantity: 8 },
      { color: "green", quantity: 8 },
      { color: "yellow", quantity: 8 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 53,
    categoryId: 0,
    name: "Áo Trúc",
    description: "Áo mới của tôi",
    price: 350,
    distance: 50,
    options: [
      { color: "red", quantity: 10 },
      { color: "purple", quantity: 10 },
      { color: "black", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 53,
    categoryId: 0,
    name: "Áo Trúc",
    description: "Áo mới của tôi",
    price: 350,
    distance: 50,
    options: [
      { color: "red", quantity: 10 },
      { color: "purple", quantity: 10 },
      { color: "black", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 54,
    categoryId: 0,
    name: "Áo Sóng",
    description: "Áo độc đáo",
    price: 400,
    distance: 50,
    options: [
      { color: "blue", quantity: 10 },
      { color: "white", quantity: 10 },
      { color: "orange", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 55,
    categoryId: 0,
    name: "Áo Hướng Dương",
    description: "Áo cực kỳ năng động",
    price: 280,
    distance: 50,
    options: [
      { color: "yellow", quantity: 10 },
      { color: "green", quantity: 10 },
      { color: "black", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 56,
    categoryId: 0,
    name: "Áo Bạch Dương",
    description: "Áo thời trang cho bạn trẻ",
    price: 420,
    distance: 50,
    options: [
      { color: "white", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "red", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 57,
    categoryId: 0,
    name: "Áo Xanh Lá",
    description: "Áo dành cho những người yêu màu xanh",
    price: 320,
    distance: 50,
    options: [
      { color: "green", quantity: 10 },
      { color: "white", quantity: 10 },
      { color: "blue", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 57,
    categoryId: 0,
    name: "Áo Mây",
    description: "Áo của tôi",
    price: 350,
    distance: 40,
    options: [
      { color: "pink", quantity: 5 },
      { color: "purple", quantity: 5 },
      { color: "white", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 58,
    categoryId: 0,
    name: "Áo Lửa",
    description: "Áo của tôi",
    price: 400,
    distance: 45,
    options: [
      { color: "red", quantity: 8 },
      { color: "orange", quantity: 8 },
      { color: "yellow", quantity: 8 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 59,
    categoryId: 0,
    name: "Áo Bụi",
    description: "Áo của tôi",
    price: 250,
    distance: 60,
    options: [
      { color: "brown", quantity: 7 },
      { color: "gray", quantity: 7 },
      { color: "black", quantity: 7 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 60,
    categoryId: 0,
    name: "Áo Nắng",
    description: "Áo của tôi",
    price: 280,
    distance: 55,
    options: [
      { color: "yellow", quantity: 12 },
      { color: "orange", quantity: 12 },
      { color: "white", quantity: 12 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ffffff",
  },
  {
    id: 61,
    categoryId: 0,
    name: "Áo Trắng",
    description: "Áo của tôi",
    price: 350,
    distance: 40,
    options: [
      { color: "blue", quantity: 15 },
      { color: "green", quantity: 15 },
      { color: "red", quantity: 15 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#ff0000",
  },
  {
    id: 62,
    categoryId: 0,
    name: "Áo Xanh Dương",
    description: "Áo của tôi",
    price: 250,
    distance: 70,
    options: [
      { color: "black", quantity: 12 },
      { color: "green", quantity: 12 },
      { color: "yellow", quantity: 12 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#f0e68c",
  },
  {
    id: 63,
    categoryId: 0,
    name: "Áo Đỏ",
    description: "Áo của tôi",
    price: 450,
    distance: 60,
    options: [
      { color: "blue", quantity: 20 },
      { color: "orange", quantity: 20 },
      { color: "pink", quantity: 20 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#8b0000",
  },
  {
    id: 64,
    categoryId: 0,
    name: "Áo Đen",
    description: "Áo của tôi",
    price: 500,
    distance: 50,
    options: [
      { color: "white", quantity: 5 },
      { color: "grey", quantity: 5 },
      { color: "brown", quantity: 5 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#a0522d",
  },
];
