export default [
  {
    id: 1,
    categoryId: 2,
    name: "mssssss",
    description: "Áo mẹ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    quantity: 5,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 2,
    categoryId: 2,
    name: "c",
    description: "Áo người yêu mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#efeef3",
  },
  {
    id: 3,
    categoryId: 2,
    name: "s",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 4,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 5,
    categoryId: 2,
    name: "b",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 6,
    categoryId: 2,
    name: "a",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 7,
    categoryId: 2,
    name: "as",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 8,
    categoryId: 2,
    name: "ss",
    description: "Áo người yêu cũ mua",
    price: 100,
    options: [
      { color: "red", quantity: 10 },
      { color: "black", quantity: 10 },
      { color: "white", quantity: 10 },
    ],
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
];
