export default [
  {
    id: 1,
    categoryId: 2,
    name: "Shirts 1",
    description: "Áo mẹ mua",
    price: 100,
    quantity: 5,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 2,
    categoryId: 2,
    name: "Shirts 2",
    description: "Áo người yêu mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#efeef3",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
  {
    id: 3,
    categoryId: 2,
    name: "shirts 3",
    description: "Áo người yêu cũ mua",
    price: 100,
    imageSource: require("../../assets/Home/Products/t-shirt-1.png"),
    backgroundColor: "#fffcfb",
  },
];
