export default [
  {
    id: 1,
    name: "Martis",
    email: "a",
    password: "a",
    address: "111",
    avatar: require("../../assets/vv.png"),
    phone: "313288",
  },
  {
    id: 1,
    name: "Nguyen Van X",
    email: "a",
    password: "a",
    address: "111",
    phone: "313288",
  },
  {
    id: 1,
    name: "Nguyen Van t",
    email: "a",
    password: "a",
    address: "111",
    phone: "313288",
  },
  {
    id: 1,
    name: "Nguyen Van 12",
    email: "v",
    password: "v",
    address: "111",
    phone: "313288",
  },
];
