export { default as Home } from "./App/Home/index";
export { default as Search } from "./App/Search/index";
export { default as Detail } from "./App/Detail/index";
export { default as GetStarted } from "./Onboarding/index";
export { default as Auth } from "./Auth/Index";
export { default as Favorite } from "./App/Favorite/index";
export { default as Cart } from "./App/Cart/index";
export { default as Profile } from "./App/Profile/index";
export { default as Main } from "./Layout/index";
